"""
app/db/base.py
──────────────────────────────────────────────────────────────────
SQLAlchemy declarative base + shared mixins.

Every table in the system inherits from `Base` and uses
`TimestampMixin` so that created_at / updated_at are automatic,
and `SoftDeleteMixin` so no row is ever hard-deleted.
"""
import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Root declarative base — all models must inherit from this."""
    pass


class TimestampMixin:
    """
    Adds created_at and updated_at columns to any model.
    Both are managed by the DB server clock, not Python.
    """
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """
    Adds deleted_at column. Records with a non-null deleted_at are
    considered deleted — never remove rows in production.
    """
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class UUIDPrimaryKeyMixin:
    """UUID primary key, auto-generated by PostgreSQL uuid_generate_v4()."""
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
